In [10]:
import numpy as np

In [11]:
#1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
vector = np.arange(10)
print(vector)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
#2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
a_matrix = np.zeros((3,3))
print(a_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
#3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
b_matrix = np.random.randint(1, 11, size=(5,5))
print(b_matrix)

[[ 2  4  7 10  2]
 [10  5  4  7  4]
 [ 4  1  5  5  1]
 [ 6  9  6  6 10]
 [ 4  8  6  6 10]]


In [14]:
#4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
c_matrix = np.random.rand(4,4)
print(c_matrix)

[[0.60857955 0.8849073  0.91542405 0.46648193]
 [0.74606419 0.0057282  0.59299912 0.90427616]
 [0.4474854  0.09736123 0.20922464 0.40054446]
 [0.55604382 0.4235939  0.3741735  0.38089869]]


In [15]:
#5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
array_a = np.random.randint(1, 11, 5)
array_b = np.random.randint(1, 11, 5)


addition = array_a + array_b
subtraction = array_a - array_b
multiplication = array_a * array_b
print(addition)
print(subtraction)
print(multiplication)

[13  5 10  9 16]
[-5  1 -4 -3  0]
[36  6 21 18 64]


In [16]:
#6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
array_a = np.random.randint(7)
array_b = np.random.randint(7)
result = np.dot(array_a, array_b)
print(result)

10


In [17]:
#7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
matrix_a = np.random.randint(1, 11, size=(2,2))
matrix_b = np.random.randint(1, 11, size=(2,3))
result = np.dot(matrix_a, matrix_b)
print(result)

[[54 60 72]
 [40 44 56]]


In [18]:
#8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
matrix = np.random.randint(1, 11, size=(2,2))
result = np.linalg.inv(matrix)
print(result)

[[-0.75   0.5  ]
 [ 0.625 -0.25 ]]


In [19]:
#9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
matrix = np.random.rand(4,4) 
print(matrix.T)

[[0.30491654 0.52588933 0.27651512 0.70799519]
 [0.72531862 0.41891967 0.81748412 0.72751502]
 [0.68143912 0.7482624  0.96448347 0.29110972]
 [0.80087801 0.26124555 0.83250406 0.77889179]]


In [20]:
#10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
matrix = np.random.randint(1, 11, size=(3,4))
array = np.random.randint(1, 11, size=4)
result = np.dot(matrix, array)
print(result)

[104 231 198]


In [21]:
#11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
matrix = np.random.rand(2,3)
array = np.random.rand(3)
result = np.dot(matrix, array)
print(result)

[0.4990178  0.88030317]


In [22]:
#12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
matrix_a = np.random.randint(1, 11, size=(2,2))
matrix_b = np.random.randint(1, 11, size=(2,2))
result = matrix_a * matrix_b
print(result)


[[42 16]
 [56  9]]


In [23]:
#13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
matrix_a = np.random.randint(1, 11, size=(2,2))
matrix_b = np.random.randint(1, 11, size=(2,2))
result = np.dot(matrix_a, matrix_b)
print(result)

[[84 63]
 [80 65]]


In [24]:
#14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
matrix = np.random.randint(1, 101, size=(5,5))
result = np.sum(matrix)
print(matrix)

[[ 91  79  76  96  61]
 [ 87  65  18  69  38]
 [ 47  72  65   7  70]
 [ 38  75  42  98  26]
 [ 17  46  68 100  95]]


In [25]:
#15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
matrix_a = np.random.randint(1, 11, size=(4,4))
matrix_b = np.random.randint(1, 11, size=(4,4))
result = matrix_a - matrix_b
print(result)

[[ 1 -9 -3 -4]
 [ 1 -4  5  2]
 [-2  5 -2 -2]
 [-2  5  7  7]]


In [26]:
#16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matrix_b = np.random.rand(3,3)
result= matrix.sum(axis=1).reshape(-1, 1)
print(result)

[[403]
 [277]
 [261]
 [279]
 [326]]


In [31]:
#17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
matrix = np.random.randint(low=0, high=1000, size=(3,4))
result = np.square(matrix)
print(result)

[[ 42025  79524 788544 289444]
 [ 64516 938961 962361 739600]
 [ 14641  29584  88804 146689]]


In [32]:
#18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
array = np.random.randint(1, 51, size=4)
result = np.sqrt(array)
print(result)

[2.         4.89897949 5.47722558 4.35889894]
